name: "Build and Release Extension"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build and Package
        # Build production unpacked first, then package it
        run: |
          bun run build
          bun run package
          ls -R build/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/chrome-mv3-prod.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Browser Platform Publisher
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: build/chrome-mv3-prod.zip
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          publish: true
